# fly.toml app configuration file generated for cesem-app on 2023-10-06T10:26:47-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cesem-app"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
