# Generated by Django 4.2 on 2023-09-19 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_visitgrass_alfalfa_dactylis_planted_hectares_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitAnimalHealth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visited_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de creación"
                    ),
                ),
                ("vaca", models.IntegerField(default=0, verbose_name="vaca")),
                (
                    "vaquillona",
                    models.IntegerField(default=0, verbose_name="vaquillona"),
                ),
                ("vaquilla", models.IntegerField(default=0, verbose_name="vaquilla")),
                ("terreno", models.IntegerField(default=0, verbose_name="terreno")),
                ("torete", models.IntegerField(default=0, verbose_name="torete")),
                ("toro", models.IntegerField(default=0, verbose_name="toro")),
                ("vacunos", models.IntegerField(default=0, verbose_name="vacunos")),
                ("ovinos", models.IntegerField(default=0, verbose_name="ovinos")),
                ("alpacas", models.IntegerField(default=0, verbose_name="alpacas")),
                ("llamas", models.IntegerField(default=0, verbose_name="llamas")),
                ("canes", models.IntegerField(default=0, verbose_name="canes")),
                (
                    "bull_name",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="nombre de toro",
                    ),
                ),
                (
                    "bull_race",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="raza de toro",
                    ),
                ),
                (
                    "pajilla_type",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="tipo pajilla",
                    ),
                ),
                (
                    "pajilla_origin",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="procedencia pajilla",
                    ),
                ),
                (
                    "pajillas_number",
                    models.IntegerField(default=0, verbose_name="nº de pajillas"),
                ),
                (
                    "cow_name",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="nombre de vaca",
                    ),
                ),
                (
                    "cow_race",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="raza de vaca",
                    ),
                ),
                (
                    "service_number",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="nº de servicio",
                    ),
                ),
                ("pregnant", models.IntegerField(default=0, verbose_name="preñada")),
                ("empty", models.IntegerField(default=0, verbose_name="vacia")),
                (
                    "birthday",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="f. nacimiento",
                    ),
                ),
                (
                    "earring_number",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="nº de arete"
                    ),
                ),
                (
                    "baby_name",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="nombre de cria",
                    ),
                ),
                (
                    "male",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="macho"
                    ),
                ),
                (
                    "female",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="hembra"
                    ),
                ),
                (
                    "death",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="muerta"
                    ),
                ),
                (
                    "baby_bull_name",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="cria-nombre de toro",
                    ),
                ),
                (
                    "baby_cow_name",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="cria-nombre de vaca",
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.activity",
                        verbose_name="actividad",
                    ),
                ),
                (
                    "diagnostic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.diagnostic",
                        verbose_name="diagnostico",
                    ),
                ),
                (
                    "employ_responsable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employ_responsable_animal",
                        to="core.person",
                        verbose_name="personal responsable",
                    ),
                ),
                (
                    "employ_specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employ_specialist_animal",
                        to="core.person",
                        verbose_name="personal especialista",
                    ),
                ),
                (
                    "production_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.productionunit",
                        verbose_name="UP",
                    ),
                ),
                (
                    "sickness_observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.sicknessobservation",
                        verbose_name="enfermedad/observación",
                    ),
                ),
            ],
            options={
                "verbose_name": "visita animal",
                "verbose_name_plural": "visitas animales",
                "ordering": ("visited_at", "production_unit"),
            },
        ),
        migrations.RenameModel(
            old_name="VisitAnimalDetails",
            new_name="VisitAnimalHealthDetails",
        ),
        migrations.DeleteModel(
            name="VisitAnimal",
        ),
        migrations.AlterField(
            model_name="visitanimalhealthdetails",
            name="visit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.visitanimalhealth"
            ),
        ),
    ]
