# Generated by Django 4.2 on 2023-06-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_visitgrass_production_unit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productionunit",
            options={
                "ordering": ("zone", "person_responsable"),
                "verbose_name": "Unidad de Producción",
                "verbose_name_plural": "Unidades de Producción",
            },
        ),
        migrations.AlterModelOptions(
            name="sector",
            options={
                "ordering": ("name",),
                "verbose_name": "sector",
                "verbose_name_plural": "sectores",
            },
        ),
        migrations.AlterModelOptions(
            name="visitanimal",
            options={
                "ordering": ("visited_at", "production_unit"),
                "verbose_name": "visita animal",
                "verbose_name_plural": "visitas animales",
            },
        ),
        migrations.AlterField(
            model_name="person",
            name="dni",
            field=models.IntegerField(blank=True, null=True, verbose_name="dni"),
        ),
    ]
