# Generated by Django 4.2 on 2023-09-21 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_visitanimalhealth_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="visitanimalhealth",
            options={
                "ordering": ("visited_at", "production_unit"),
                "verbose_name": "visita sanidad animal",
                "verbose_name_plural": "visitas sanidad animal",
            },
        ),
        migrations.AlterModelOptions(
            name="visitanimalhealthdetails",
            options={
                "verbose_name": "visita sanidad animal - detalle",
                "verbose_name_plural": "visitas sanidad animal - detalles",
            },
        ),
        migrations.RemoveField(
            model_name="visitanimalhealth",
            name="baby_bull_name",
        ),
        migrations.RemoveField(
            model_name="visitanimalhealth",
            name="baby_cow_name",
        ),
        migrations.RemoveField(
            model_name="visitanimalhealth",
            name="baby_name",
        ),
        migrations.RemoveField(
            model_name="visitanimalhealth",
            name="birthday",
        ),
        migrations.RemoveField(
            model_name="visitanimalhealth",
            name="bull_name",
        ),
        migrations.RemoveField(
            model_name="visitanimalhealth",
            name="bull_race",
        ),
        migrations.RemoveField(
            model_name="visitanimalhealth",
            name="cow_name",
        ),
        migrations.RemoveField(
            model_name="visitanimalhealth",
            name="cow_race",
        ),
        migrations.RemoveField(
            model_name="visitanimalhealth",
            name="death",
        ),
        migrations.RemoveField(
            model_name="visitanimalhealth",
            name="earring_number",
        ),
        migrations.RemoveField(
            model_name="visitanimalhealth",
            name="empty",
        ),
        migrations.RemoveField(
            model_name="visitanimalhealth",
            name="female",
        ),
        migrations.RemoveField(
            model_name="visitanimalhealth",
            name="male",
        ),
        migrations.RemoveField(
            model_name="visitanimalhealth",
            name="pajilla_origin",
        ),
        migrations.RemoveField(
            model_name="visitanimalhealth",
            name="pajilla_type",
        ),
        migrations.RemoveField(
            model_name="visitanimalhealth",
            name="pajillas_number",
        ),
        migrations.RemoveField(
            model_name="visitanimalhealth",
            name="pregnant",
        ),
        migrations.RemoveField(
            model_name="visitanimalhealth",
            name="service_number",
        ),
        migrations.AlterField(
            model_name="productionunit",
            name="is_pilot",
            field=models.BooleanField(default=False, verbose_name="UP es piloto?"),
        ),
        migrations.AlterField(
            model_name="productionunit",
            name="tipology",
            field=models.IntegerField(default=0, verbose_name="tipología de UP"),
        ),
        migrations.AlterField(
            model_name="visitanimalhealth",
            name="visited_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="fecha de visita"
            ),
        ),
        migrations.AlterField(
            model_name="visitgrass",
            name="visited_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="fecha de visita"
            ),
        ),
        migrations.CreateModel(
            name="VisitGeneticImprovementVacuno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visited_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de visita"
                    ),
                ),
                (
                    "bull_name",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="nombre de toro",
                    ),
                ),
                (
                    "bull_race",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="raza de toro",
                    ),
                ),
                (
                    "pajilla_type",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="tipo pajilla",
                    ),
                ),
                (
                    "pajilla_origin",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="procedencia pajilla",
                    ),
                ),
                (
                    "pajillas_number",
                    models.IntegerField(default=0, verbose_name="nº de pajillas"),
                ),
                (
                    "cow_name",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="nombre de vaca",
                    ),
                ),
                (
                    "cow_race",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="raza de vaca",
                    ),
                ),
                (
                    "service_number",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="nº de servicio",
                    ),
                ),
                ("pregnant", models.IntegerField(default=0, verbose_name="preñada")),
                ("empty", models.IntegerField(default=0, verbose_name="vacia")),
                (
                    "birthday",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="f. nacimiento",
                    ),
                ),
                (
                    "earring_number",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="nº de arete"
                    ),
                ),
                (
                    "baby_name",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="nombre de cria",
                    ),
                ),
                (
                    "male",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="macho"
                    ),
                ),
                (
                    "female",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="hembra"
                    ),
                ),
                (
                    "death",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="muerta"
                    ),
                ),
                (
                    "baby_bull_name",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="cria-nombre de toro",
                    ),
                ),
                (
                    "baby_cow_name",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="cria-nombre de vaca",
                    ),
                ),
                (
                    "generic_improvement_type",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="tipo de mejoramiento genético",
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.activity",
                        verbose_name="actividad",
                    ),
                ),
                (
                    "employ_responsable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employ_responsable_vacuno",
                        to="core.person",
                        verbose_name="personal responsable",
                    ),
                ),
                (
                    "employ_specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employ_specialist_vacuno",
                        to="core.person",
                        verbose_name="personal especialista",
                    ),
                ),
                (
                    "production_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.productionunit",
                        verbose_name="UP",
                    ),
                ),
            ],
            options={
                "verbose_name": "visita MG vacuno",
                "verbose_name_plural": "visitas MG vacunos",
            },
        ),
        migrations.CreateModel(
            name="VisitGeneticImprovementOvino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visited_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de visita"
                    ),
                ),
                (
                    "selected_ovines",
                    models.IntegerField(default=0, verbose_name="ovinos seleccionados"),
                ),
                (
                    "synchronized_ovines",
                    models.IntegerField(default=0, verbose_name="ovinos sincronizados"),
                ),
                (
                    "inseminated_sheeps_corriedale",
                    models.IntegerField(
                        default=0, verbose_name="ovejas inseminadas corriedale"
                    ),
                ),
                (
                    "inseminated_sheeps_criollas",
                    models.IntegerField(
                        default=0, verbose_name="ovenas inseminadas criollas"
                    ),
                ),
                ("pregnant", models.IntegerField(default=0, verbose_name="preñadas")),
                ("empty", models.IntegerField(default=0, verbose_name="vacías")),
                (
                    "not_evaluated",
                    models.IntegerField(default=0, verbose_name="no evaluadas"),
                ),
                (
                    "baby_males",
                    models.IntegerField(default=0, verbose_name="crias machos"),
                ),
                (
                    "baby_females",
                    models.IntegerField(default=0, verbose_name="crias hembras"),
                ),
                (
                    "baby_deaths",
                    models.IntegerField(default=0, verbose_name="crias muertas"),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.activity",
                        verbose_name="actividad",
                    ),
                ),
                (
                    "employ_responsable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employ_responsable_ovino",
                        to="core.person",
                        verbose_name="personal responsable",
                    ),
                ),
                (
                    "employ_specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employ_specialist_ovino",
                        to="core.person",
                        verbose_name="personal especialista",
                    ),
                ),
                (
                    "production_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.productionunit",
                        verbose_name="UP",
                    ),
                ),
            ],
            options={
                "verbose_name": "visita MG ovino",
                "verbose_name_plural": "visitas MG ovinos",
            },
        ),
        migrations.CreateModel(
            name="VisitGeneticImprovementAlpaca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visited_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de visita"
                    ),
                ),
                (
                    "hato_number",
                    models.IntegerField(default=0, verbose_name="nº de hato"),
                ),
                (
                    "hato_babies_number",
                    models.IntegerField(default=0, verbose_name="nº de crias en hato"),
                ),
                (
                    "hato_mothers_number",
                    models.IntegerField(default=0, verbose_name="nº de madres en hato"),
                ),
                (
                    "hato_males_number",
                    models.IntegerField(default=0, verbose_name="nº de machos en hato"),
                ),
                (
                    "female_alpaca_earring_number",
                    models.IntegerField(
                        default=0, verbose_name="nº arete alpaca hembra"
                    ),
                ),
                (
                    "female_alpaca_race",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="raza alpaca hembra",
                    ),
                ),
                (
                    "female_alpaca_color",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="color alpaca hembra",
                    ),
                ),
                (
                    "female_alpaca_age",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="edad alpaca hembra",
                    ),
                ),
                (
                    "female_alpaca_category",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="categoria alpaca hembra",
                    ),
                ),
                (
                    "female_alpaca_total_score",
                    models.IntegerField(
                        default=0, verbose_name="puntaje total alpaca hembra"
                    ),
                ),
                (
                    "empadre_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha empadre"
                    ),
                ),
                (
                    "alpacas_empadradas",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="alpacas empadradas",
                    ),
                ),
                (
                    "alpacas_empadradas_number",
                    models.IntegerField(
                        default=0, verbose_name="nº de alpacas empadradas"
                    ),
                ),
                (
                    "male_empadre_number",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="nº macho empadre",
                    ),
                ),
                (
                    "second_service_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha 2do servicio"
                    ),
                ),
                (
                    "second_service_male_number",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="nº macho 2do servicio",
                    ),
                ),
                ("pregnant", models.IntegerField(default=0, verbose_name="preñada")),
                ("empty", models.IntegerField(default=0, verbose_name="vacía")),
                (
                    "baby_birthday",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha nacimiento cria"
                    ),
                ),
                (
                    "baby_earring_number",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="nº de arete cria",
                    ),
                ),
                (
                    "female_baby",
                    models.IntegerField(default=0, verbose_name="cria hembra"),
                ),
                (
                    "male_baby",
                    models.IntegerField(default=0, verbose_name="cria macho"),
                ),
                (
                    "mortality_baby",
                    models.IntegerField(default=0, verbose_name="mortandad cria"),
                ),
                (
                    "mother_of_baby",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="madre de cria",
                    ),
                ),
                (
                    "father_of_baby",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="padre de cria",
                    ),
                ),
                (
                    "training_male_assistance",
                    models.IntegerField(default=0, verbose_name="capac asist varones"),
                ),
                (
                    "training_female_assistance",
                    models.IntegerField(default=0, verbose_name="capac asist mujeres"),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.activity",
                        verbose_name="actividad",
                    ),
                ),
                (
                    "employ_responsable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employ_responsable_alpaca",
                        to="core.person",
                        verbose_name="personal responsable",
                    ),
                ),
                (
                    "employ_specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employ_specialist_alpaca",
                        to="core.person",
                        verbose_name="personal especialista",
                    ),
                ),
                (
                    "production_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.productionunit",
                        verbose_name="UP",
                    ),
                ),
            ],
            options={
                "verbose_name": "visita MG alpaca",
                "verbose_name_plural": "visitas MG alpacas",
            },
        ),
    ]
