# Generated by Django 4.2 on 2023-09-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_visitanimalhealth_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visitgeneticimprovementalpaca",
            name="training_female_assistance",
        ),
        migrations.RemoveField(
            model_name="visitgeneticimprovementalpaca",
            name="training_male_assistance",
        ),
        migrations.RemoveField(
            model_name="visitgeneticimprovementvacuno",
            name="generic_improvement_type",
        ),
        migrations.AddField(
            model_name="visitgeneticimprovementalpaca",
            name="selected_alpacas_number",
            field=models.IntegerField(
                default=0, verbose_name="selec cant alpacas seleccionadas"
            ),
        ),
        migrations.AddField(
            model_name="visitgeneticimprovementalpaca",
            name="technical_assistance_attendance",
            field=models.IntegerField(
                default=0, verbose_name="asist tec buenas prácticas manejo alpacas"
            ),
        ),
        migrations.AddField(
            model_name="visitgeneticimprovementalpaca",
            name="training_female_attendance",
            field=models.IntegerField(default=0, verbose_name="asist mujeres capac"),
        ),
        migrations.AddField(
            model_name="visitgeneticimprovementalpaca",
            name="training_male_attendance",
            field=models.IntegerField(default=0, verbose_name="asist varones capac"),
        ),
        migrations.AddField(
            model_name="visitgeneticimprovementovino",
            name="course_female_attendance",
            field=models.IntegerField(
                default=0, verbose_name="asis mujeres curso manejo ovinos"
            ),
        ),
        migrations.AddField(
            model_name="visitgeneticimprovementovino",
            name="course_male_attendance",
            field=models.IntegerField(
                default=0, verbose_name="asis varones curso manejo ovinos"
            ),
        ),
        migrations.AddField(
            model_name="visitgeneticimprovementovino",
            name="technical_assistance_attendance",
            field=models.IntegerField(
                default=0, verbose_name="asis tec producción ganado ovino corriedale"
            ),
        ),
        migrations.AddField(
            model_name="visitgeneticimprovementvacuno",
            name="female_attendance",
            field=models.IntegerField(
                default=0, verbose_name="asis mujeres capac manejo reproductivo"
            ),
        ),
        migrations.AddField(
            model_name="visitgeneticimprovementvacuno",
            name="male_attendance",
            field=models.IntegerField(
                default=0, verbose_name="asis varones capac manejo reproductivo"
            ),
        ),
        migrations.AlterField(
            model_name="visitgeneticimprovementalpaca",
            name="female_alpaca_age",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                verbose_name="selec edad alpaca hembra",
            ),
        ),
        migrations.AlterField(
            model_name="visitgeneticimprovementalpaca",
            name="female_alpaca_category",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                verbose_name="selec categoria alpaca hembra",
            ),
        ),
        migrations.AlterField(
            model_name="visitgeneticimprovementalpaca",
            name="female_alpaca_color",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                verbose_name="selec color alpaca hembra",
            ),
        ),
        migrations.AlterField(
            model_name="visitgeneticimprovementalpaca",
            name="female_alpaca_earring_number",
            field=models.IntegerField(
                default=0, verbose_name="selec nº arete alpaca hembra"
            ),
        ),
        migrations.AlterField(
            model_name="visitgeneticimprovementalpaca",
            name="female_alpaca_race",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                verbose_name="selec raza alpaca hembra",
            ),
        ),
        migrations.AlterField(
            model_name="visitgeneticimprovementalpaca",
            name="female_alpaca_total_score",
            field=models.IntegerField(
                default=0, verbose_name="selec puntaje total alpaca hembra"
            ),
        ),
    ]
