# Generated by Django 4.2 on 2023-06-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_productionunit_options_alter_sector_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="visitanimal",
            old_name="sheep",
            new_name="ovinos",
        ),
        migrations.RenameField(
            model_name="visitanimal",
            old_name="cattle",
            new_name="vacunos",
        ),
        migrations.AddField(
            model_name="visitanimal",
            name="terreno",
            field=models.IntegerField(default=0, verbose_name="terreno"),
        ),
        migrations.AddField(
            model_name="visitanimal",
            name="torete",
            field=models.IntegerField(default=0, verbose_name="torete"),
        ),
        migrations.AddField(
            model_name="visitanimal",
            name="toro",
            field=models.IntegerField(default=0, verbose_name="toro"),
        ),
        migrations.AddField(
            model_name="visitanimal",
            name="vaca",
            field=models.IntegerField(default=0, verbose_name="vaca"),
        ),
        migrations.AddField(
            model_name="visitanimal",
            name="vaquilla",
            field=models.IntegerField(default=0, verbose_name="vaquilla"),
        ),
        migrations.AddField(
            model_name="visitanimal",
            name="vaquillona",
            field=models.IntegerField(default=0, verbose_name="vaquillona"),
        ),
    ]
