# Generated by Django 4.2 on 2023-09-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0005_remove_visitgeneticimprovementalpaca_training_female_assistance_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="visitgeneticimprovementovino",
            name="ovinos_number",
            field=models.IntegerField(default=0, verbose_name="cant ovinos"),
        ),
        migrations.AddField(
            model_name="visitgeneticimprovementvacuno",
            name="technical_assistance_attendance",
            field=models.IntegerField(
                default=0, verbose_name="asis tec manejo ganado vacuno lechero"
            ),
        ),
        migrations.AddField(
            model_name="visitgeneticimprovementvacuno",
            name="vacunos_number",
            field=models.IntegerField(default=0, verbose_name="cant vacunos"),
        ),
    ]
