# Generated by Django 4.2 on 2023-06-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_rename_sheep_visitanimal_ovinos_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FilesChecksum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_created=True, auto_now=True)),
                ("checksum", models.CharField(max_length=100)),
            ],
        ),
    ]
