# Generated by Django 4.2 on 2023-06-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_fileschecksum"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileschecksum",
            name="filename",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
