# Generated by Django 4.2 on 2023-09-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_visitgeneticimprovementovino_ovinos_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitgeneticimprovementvacuno",
            name="death",
            field=models.IntegerField(default=0, verbose_name="muerta"),
        ),
        migrations.AlterField(
            model_name="visitgeneticimprovementvacuno",
            name="female",
            field=models.IntegerField(default=0, verbose_name="hembra"),
        ),
        migrations.AlterField(
            model_name="visitgeneticimprovementvacuno",
            name="male",
            field=models.IntegerField(default=0, verbose_name="macho"),
        ),
    ]
