# Generated by Django 4.2 on 2023-09-30 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_visitgeneticimprovementvacuno_death_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitgeneticimprovementovino",
            name="rgc_number",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="nº RGC"
            ),
        ),
    ]
