# Generated by Django 4.2 on 2023-06-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_fileschecksum_filename"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visitgrass",
            name="quantity",
        ),
        migrations.AddField(
            model_name="visitgrass",
            name="alfalfa_dactylis_planted_hectares",
            field=models.IntegerField(
                default=0, verbose_name="has. siembra alfalfa dactylis"
            ),
        ),
        migrations.AddField(
            model_name="visitgrass",
            name="avena_vicia_planted_hectares",
            field=models.IntegerField(
                default=0, verbose_name="has. siembra avena/vicia"
            ),
        ),
        migrations.AddField(
            model_name="visitgrass",
            name="bale",
            field=models.IntegerField(default=0, verbose_name="pacas %"),
        ),
        migrations.AddField(
            model_name="visitgrass",
            name="direct_grazing",
            field=models.IntegerField(default=0, verbose_name="pastoreo directo %"),
        ),
        migrations.AddField(
            model_name="visitgrass",
            name="ensilage",
            field=models.IntegerField(default=0, verbose_name="ensilado %"),
        ),
        migrations.AddField(
            model_name="visitgrass",
            name="harvest_evaluation_kg",
            field=models.IntegerField(default=0, verbose_name="eval.cosecha kg mv/ha "),
        ),
        migrations.AddField(
            model_name="visitgrass",
            name="hay",
            field=models.IntegerField(default=0, verbose_name="heno %"),
        ),
        migrations.AddField(
            model_name="visitgrass",
            name="perennial_grazing",
            field=models.IntegerField(default=0, verbose_name="pastoreo perenne %"),
        ),
        migrations.AddField(
            model_name="visitgrass",
            name="perennial_yield",
            field=models.IntegerField(default=0, verbose_name="rendimiento perenne kg"),
        ),
        migrations.AddField(
            model_name="visitgrass",
            name="planting_intention_hectares",
            field=models.IntegerField(default=0, verbose_name="has. inten. siembra"),
        ),
        migrations.AddField(
            model_name="visitgrass",
            name="raygrass_trebol_planted_hectares",
            field=models.IntegerField(
                default=0, verbose_name="has. siembra raygrass trebol"
            ),
        ),
        migrations.AddField(
            model_name="visitgrass",
            name="technical_assistance_has",
            field=models.IntegerField(default=0, verbose_name="asistencia técnica"),
        ),
    ]
