# Generated by Django 4.2 on 2023-10-01 00:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_visitgeneticimprovementovino_rgc_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitgeneticimprovementalpaca",
            name="female_alpaca_earring_number",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                verbose_name="selec nº arete alpaca hembra",
            ),
        ),
    ]
