# Generated by Django 4.2 on 2023-06-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_remove_visitgrass_quantity_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="diagnostic",
            options={
                "ordering": ("name",),
                "verbose_name": "diagnostico",
                "verbose_name_plural": "diagnosticos",
            },
        ),
        migrations.AlterField(
            model_name="drug",
            name="um",
            field=models.CharField(max_length=100, verbose_name="unidad de medida"),
        ),
    ]
