# Generated by Django 4.2 on 2023-10-01 01:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0009_alter_visitgeneticimprovementalpaca_female_alpaca_earring_number",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="position",
            field=models.CharField(max_length=10, verbose_name="posición"),
        ),
    ]
