# Generated by Django 4.2 on 2023-10-06 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_activity_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="zone_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="zone_2",
                to="core.zone",
                verbose_name="zona 2",
            ),
        ),
    ]
