# Generated by Django 4.2 on 2023-06-30 05:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_remove_visitgrass_harvest_evaluation_kg_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visitgrass",
            name="alfalfa_dactylis_planted_hectares",
        ),
        migrations.RemoveField(
            model_name="visitgrass",
            name="avena_vicia_planted_hectares",
        ),
        migrations.RemoveField(
            model_name="visitgrass",
            name="bale",
        ),
        migrations.RemoveField(
            model_name="visitgrass",
            name="direct_grazing",
        ),
        migrations.RemoveField(
            model_name="visitgrass",
            name="ensilage",
        ),
        migrations.RemoveField(
            model_name="visitgrass",
            name="hay",
        ),
        migrations.RemoveField(
            model_name="visitgrass",
            name="perennial_grazing",
        ),
        migrations.RemoveField(
            model_name="visitgrass",
            name="perennial_yield",
        ),
        migrations.RemoveField(
            model_name="visitgrass",
            name="planting_intention_hectares",
        ),
        migrations.RemoveField(
            model_name="visitgrass",
            name="raygrass_trebol_planted_hectares",
        ),
    ]
