# Generated by Django 4.2 on 2023-10-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_sector_community_2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sector",
            name="name",
            field=models.CharField(max_length=50, unique=True, verbose_name="nombre"),
        ),
    ]
