# Generated by Django 4.2 on 2023-07-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_remove_visitgrass_alfalfa_dactylis_planted_hectares_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitgrass",
            name="producer_classification",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                verbose_name="tipificación de productores",
            ),
        ),
    ]
