# Generated by Django 4.2 on 2023-07-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_visitgrass_producer_classification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitgrass",
            name="quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="cantidad",
            ),
        ),
    ]
