# Generated by Django 4.2 on 2023-10-06 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_alter_sector_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="sector",
            name="community_3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comunidad_3",
                to="core.community",
                verbose_name="comunidad 3",
            ),
        ),
    ]
