# Generated by Django 4.2 on 2023-10-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_sector_community_3"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fileschecksum",
            options={
                "ordering": ("created_at",),
                "verbose_name": "Archivo Subido",
                "verbose_name_plural": "Archivos Subidos",
            },
        ),
        migrations.AddField(
            model_name="fileschecksum",
            name="rows",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="visitanimalhealth",
            name="checksum",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="visitgeneticimprovementalpaca",
            name="checksum",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="visitgeneticimprovementovino",
            name="checksum",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="visitgeneticimprovementvacuno",
            name="checksum",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="visitgrass",
            name="checksum",
            field=models.CharField(default="", max_length=100),
        ),
    ]
