# Generated by Django 4.2 on 2023-07-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_alter_visitgrass_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitgrass",
            name="bale",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="pacas (%)",
            ),
        ),
        migrations.AddField(
            model_name="visitgrass",
            name="direct_grazing",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="pastoreo directo (%)",
            ),
        ),
        migrations.AddField(
            model_name="visitgrass",
            name="ensilage",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="ensilado (%)",
            ),
        ),
        migrations.AddField(
            model_name="visitgrass",
            name="hay",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="heno (%)",
            ),
        ),
        migrations.AddField(
            model_name="visitgrass",
            name="perennial_ensilage",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="ensilado % perenne",
            ),
        ),
        migrations.AddField(
            model_name="visitgrass",
            name="perennial_grazing",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="pastoreo % perenne",
            ),
        ),
    ]
