# Generated by Django 4.2 on 2023-10-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_alter_fileschecksum_options_fileschecksum_rows_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fileschecksum",
            name="rows",
        ),
        migrations.AddField(
            model_name="fileschecksum",
            name="visits",
            field=models.IntegerField(default=0, verbose_name="visitas"),
        ),
        migrations.AlterField(
            model_name="fileschecksum",
            name="created_at",
            field=models.DateTimeField(
                auto_created=True, auto_now=True, verbose_name="f. creación"
            ),
        ),
        migrations.AlterField(
            model_name="fileschecksum",
            name="filename",
            field=models.TextField(verbose_name="nombre"),
        ),
    ]
