# Generated by Django 4.2 on 2023-10-12 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_remove_fileschecksum_rows_fileschecksum_visits_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productionunit",
            name="person_member",
        ),
        migrations.AddField(
            model_name="visitanimalhealth",
            name="up_member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="person_member_animal",
                to="core.person",
                verbose_name="up. integrante",
            ),
        ),
        migrations.AddField(
            model_name="visitgeneticimprovementalpaca",
            name="up_member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="person_member_animal_alpaca",
                to="core.person",
                verbose_name="up. integrante",
            ),
        ),
        migrations.AddField(
            model_name="visitgeneticimprovementovino",
            name="up_member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="person_member_animal_ovino",
                to="core.person",
                verbose_name="up. integrante",
            ),
        ),
        migrations.AddField(
            model_name="visitgeneticimprovementvacuno",
            name="up_member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="person_member_animal_vacuno",
                to="core.person",
                verbose_name="up. integrante",
            ),
        ),
        migrations.AddField(
            model_name="visitgrass",
            name="up_member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="person_member_grass",
                to="core.person",
                verbose_name="up. integrante",
            ),
        ),
        migrations.AlterField(
            model_name="community",
            name="name",
            field=models.CharField(max_length=20, verbose_name="nombre"),
        ),
        migrations.AlterField(
            model_name="visitgeneticimprovementvacuno",
            name="production_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.productionunit",
                verbose_name="UP",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="person",
            unique_together={("dni", "name")},
        ),
    ]
