# Generated by Django 4.2 on 2023-10-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_remove_productionunit_person_member_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="name",
            field=models.CharField(max_length=50, verbose_name="nombre"),
        ),
    ]
