# Generated by Django 4.2 on 2023-10-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_alter_community_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="meta_2022",
            field=models.IntegerField(default=0, verbose_name="meta 2022"),
        ),
        migrations.AddField(
            model_name="activity",
            name="meta_2023",
            field=models.IntegerField(default=0, verbose_name="meta 2023"),
        ),
        migrations.AddField(
            model_name="activity",
            name="meta_2024",
            field=models.IntegerField(default=0, verbose_name="meta 2024"),
        ),
    ]
