# Generated by Django 4.2 on 2023-10-19 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_activity_meta_2022_activity_meta_2023_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitComponents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parte_number",
                    models.IntegerField(default=0, verbose_name="nro. parte"),
                ),
                (
                    "year",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="año"
                    ),
                ),
                (
                    "visited_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de visita"
                    ),
                ),
                ("age", models.IntegerField(default=0, verbose_name="edad")),
                ("quantity", models.IntegerField(default=0, verbose_name="cantidad")),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.activity",
                        verbose_name="actividad",
                    ),
                ),
                (
                    "production_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.productionunit",
                        verbose_name="UP",
                    ),
                ),
                (
                    "specialist_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specialist_employee",
                        to="core.person",
                        verbose_name="especialista de cadenas",
                    ),
                ),
                (
                    "technical_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technical_employee",
                        to="core.person",
                        verbose_name="técnico de cadenas",
                    ),
                ),
                (
                    "trainer_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainer_employee",
                        to="core.person",
                        verbose_name="capacitador",
                    ),
                ),
            ],
        ),
    ]
