# Generated by Django 4.2 on 2023-10-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_visitcomponents"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitcomponents",
            name="certificate_delivery",
            field=models.IntegerField(
                default=0, verbose_name="entrega de certificados gestión empresarial"
            ),
        ),
        migrations.AddField(
            model_name="visitcomponents",
            name="general_data",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="datos generales"
            ),
        ),
        migrations.AddField(
            model_name="visitcomponents",
            name="pedagogical_process",
            field=models.IntegerField(
                default=0, verbose_name="procesos pedagógicos equipo cesem"
            ),
        ),
    ]
