# Generated by Django 4.2 on 2023-10-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_visitcomponents_certificate_delivery_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitcomponents",
            name="age",
            field=models.IntegerField(default=0, verbose_name="edad RUP"),
        ),
    ]
