# Generated by Django 4.2 on 2023-10-20 12:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_alter_visitcomponents_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="visitcomponents",
            options={
                "verbose_name": "visita componente ii y iii",
                "verbose_name_plural": "visitas componentes ii y iii",
            },
        ),
    ]
