# Generated by Django 4.2 on 2023-10-30 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_alter_visitcomponents_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="sum_in_parent",
            field=models.BooleanField(default=True, verbose_name="sumar en resumen"),
        ),
    ]
