# Generated by Django 4.2 on 2023-11-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_activity_sum_in_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="name",
            field=models.CharField(max_length=500, verbose_name="nombre"),
        ),
    ]
