# Generated by Django 4.2 on 2024-02-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_productionunit_is_official"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnualPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_from",
                    models.DateField(verbose_name="fecha de inicio de periodo"),
                ),
            ],
            options={
                "verbose_name": "Periodo anual",
            },
        ),
    ]
