# Generated by Django 4.2 on 2024-02-19 18:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_anualperiod"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="anualperiod",
            options={
                "verbose_name": "Periodo anual",
                "verbose_name_plural": "Periodo anual",
            },
        ),
    ]
