# Generated by Django 4.2 on 2024-06-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_alter_anualperiod_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productionunit",
            options={
                "ordering": ("person_responsable__name", "zone"),
                "verbose_name": "Unidad de Producción",
                "verbose_name_plural": "Unidades de Producción",
            },
        ),
        migrations.RemoveField(
            model_name="person",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="visitanimalhealth",
            name="up_member",
        ),
        migrations.RemoveField(
            model_name="visitgeneticimprovementalpaca",
            name="up_member",
        ),
        migrations.RemoveField(
            model_name="visitgeneticimprovementovino",
            name="up_member",
        ),
        migrations.RemoveField(
            model_name="visitgeneticimprovementvacuno",
            name="up_member",
        ),
        migrations.RemoveField(
            model_name="visitgrass",
            name="up_member",
        ),
        migrations.AddField(
            model_name="visitanimalhealth",
            name="sex",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "femenino"), (1, "masculino")],
                null=True,
                verbose_name="sexo IUP",
            ),
        ),
        migrations.AddField(
            model_name="visitanimalhealth",
            name="up_member_dni",
            field=models.CharField(
                blank=True, default="", max_length=20, null=True, verbose_name="N dni"
            ),
        ),
        migrations.AddField(
            model_name="visitanimalhealth",
            name="up_member_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                null=True,
                verbose_name="UP integrante",
            ),
        ),
        migrations.AddField(
            model_name="visitgeneticimprovementalpaca",
            name="sex",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "femenino"), (1, "masculino")],
                null=True,
                verbose_name="sexo IUP",
            ),
        ),
        migrations.AddField(
            model_name="visitgeneticimprovementalpaca",
            name="up_member_dni",
            field=models.CharField(
                blank=True, default="", max_length=20, null=True, verbose_name="N dni"
            ),
        ),
        migrations.AddField(
            model_name="visitgeneticimprovementalpaca",
            name="up_member_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                null=True,
                verbose_name="UP integrante",
            ),
        ),
        migrations.AddField(
            model_name="visitgeneticimprovementovino",
            name="sex",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "femenino"), (1, "masculino")],
                null=True,
                verbose_name="sexo IUP",
            ),
        ),
        migrations.AddField(
            model_name="visitgeneticimprovementovino",
            name="up_member_dni",
            field=models.CharField(
                blank=True, default="", max_length=20, null=True, verbose_name="N dni"
            ),
        ),
        migrations.AddField(
            model_name="visitgeneticimprovementovino",
            name="up_member_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                null=True,
                verbose_name="UP integrante",
            ),
        ),
        migrations.AddField(
            model_name="visitgeneticimprovementvacuno",
            name="sex",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "femenino"), (1, "masculino")],
                null=True,
                verbose_name="sexo IUP",
            ),
        ),
        migrations.AddField(
            model_name="visitgeneticimprovementvacuno",
            name="up_member_dni",
            field=models.CharField(
                blank=True, default="", max_length=20, null=True, verbose_name="N dni"
            ),
        ),
        migrations.AddField(
            model_name="visitgeneticimprovementvacuno",
            name="up_member_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                null=True,
                verbose_name="UP integrante",
            ),
        ),
        migrations.AddField(
            model_name="visitgrass",
            name="sex",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "femenino"), (1, "masculino")],
                null=True,
                verbose_name="sexo IUP",
            ),
        ),
        migrations.AddField(
            model_name="visitgrass",
            name="up_member_dni",
            field=models.CharField(
                blank=True, default="", max_length=20, null=True, verbose_name="N dni"
            ),
        ),
        migrations.AddField(
            model_name="visitgrass",
            name="up_member_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                null=True,
                verbose_name="UP integrante",
            ),
        ),
    ]
