# Generated by Django 4.2 on 2024-06-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_alter_productionunit_options_remove_person_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnostic",
            name="name",
            field=models.CharField(max_length=100, verbose_name="observación"),
        ),
    ]
