# Generated by Django 4.2 on 2024-06-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_alter_diagnostic_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sicknessobservation",
            name="name",
            field=models.CharField(max_length=100, verbose_name="nombre"),
        ),
    ]
