# Generated by Django 4.2 on 2024-07-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_alter_sicknessobservation_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drug",
            name="name",
            field=models.CharField(max_length=100, verbose_name="nombre"),
        ),
    ]
