# Generated by Django 4.2 on 2024-08-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_alter_drug_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionunit",
            name="created_at",
            field=models.DateTimeField(
                auto_created=True, auto_now=True, verbose_name="f. creación"
            ),
        ),
        migrations.AddField(
            model_name="visitanimalhealth",
            name="created_at",
            field=models.DateTimeField(
                auto_created=True, auto_now=True, verbose_name="f. creación"
            ),
        ),
        migrations.AddField(
            model_name="visitcomponents",
            name="created_at",
            field=models.DateTimeField(
                auto_created=True, auto_now=True, verbose_name="f. creación"
            ),
        ),
        migrations.AddField(
            model_name="visitgeneticimprovementalpaca",
            name="created_at",
            field=models.DateTimeField(
                auto_created=True, auto_now=True, verbose_name="f. creación"
            ),
        ),
        migrations.AddField(
            model_name="visitgeneticimprovementovino",
            name="created_at",
            field=models.DateTimeField(
                auto_created=True, auto_now=True, verbose_name="f. creación"
            ),
        ),
        migrations.AddField(
            model_name="visitgeneticimprovementvacuno",
            name="created_at",
            field=models.DateTimeField(
                auto_created=True, auto_now=True, verbose_name="f. creación"
            ),
        ),
        migrations.AddField(
            model_name="visitgrass",
            name="created_at",
            field=models.DateTimeField(
                auto_created=True, auto_now=True, verbose_name="f. creación"
            ),
        ),
    ]
