# Generated by Django 4.2 on 2024-11-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_alter_drug_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visitcomponents",
            name="year",
        ),
        migrations.AddField(
            model_name="visitcomponents",
            name="month",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="mes"
            ),
        ),
    ]
