# Generated by Django 4.2 on 2024-11-04 15:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_remove_visitcomponents_year_visitcomponents_month"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visitcomponents",
            name="certificate_delivery",
        ),
        migrations.RemoveField(
            model_name="visitcomponents",
            name="pedagogical_process",
        ),
    ]
