# Generated by Django 4.2 on 2024-07-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_visitanimaldeworming_visitcomponent2_visitcomponent3_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitcomponent3",
            name="created_at",
            field=models.DateTimeField(
                auto_created=True, auto_now=True, verbose_name="f. creación"
            ),
        ),
    ]
