# Generated by Django 4.2 on 2024-08-22 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_visitanimaldeworming"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="visitanimaldeworming",
            options={
                "ordering": ("visited_at", "production_unit"),
                "verbose_name": "visita vacunacion",
                "verbose_name_plural": "visitas vacunacion",
            },
        ),
        migrations.AlterField(
            model_name="visitanimalhealth",
            name="diagnostic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.diagnostic",
                verbose_name="diagnostico",
            ),
        ),
        migrations.AlterField(
            model_name="visitanimalhealth",
            name="sickness_observation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.sicknessobservation",
                verbose_name="enfermedad/observación",
            ),
        ),
    ]
