# Generated by Django 4.2 on 2024-11-04 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_remove_visitcomponents_certificate_delivery_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitComponent2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parte_number",
                    models.IntegerField(default=0, verbose_name="nro. parte"),
                ),
                (
                    "month",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="mes"
                    ),
                ),
                (
                    "visited_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de visita"
                    ),
                ),
                (
                    "general_data",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="datos generales",
                    ),
                ),
                ("age", models.IntegerField(default=0, verbose_name="edad RUP")),
                ("quantity", models.IntegerField(default=0, verbose_name="cantidad")),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.activity",
                        verbose_name="actividad",
                    ),
                ),
                (
                    "production_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.productionunit",
                        verbose_name="UP",
                    ),
                ),
                (
                    "specialist_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specialist_employee_c2",
                        to="core.person",
                        verbose_name="especialista de cadenas",
                    ),
                ),
                (
                    "technical_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technical_employee_c2",
                        to="core.person",
                        verbose_name="técnico de cadenas",
                    ),
                ),
                (
                    "trainer_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainer_employee_c2",
                        to="core.person",
                        verbose_name="capacitador",
                    ),
                ),
            ],
            options={
                "verbose_name": "visita componente ii",
                "verbose_name_plural": "visitas componente ii",
            },
        ),
        migrations.CreateModel(
            name="VisitComponent3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parte_number",
                    models.IntegerField(default=0, verbose_name="nro. parte"),
                ),
                (
                    "month",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="mes"
                    ),
                ),
                (
                    "visited_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de visita"
                    ),
                ),
                (
                    "general_data",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="datos generales",
                    ),
                ),
                ("age", models.IntegerField(default=0, verbose_name="edad RUP")),
                ("quantity", models.IntegerField(default=0, verbose_name="cantidad")),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.activity",
                        verbose_name="actividad",
                    ),
                ),
                (
                    "production_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.productionunit",
                        verbose_name="UP",
                    ),
                ),
                (
                    "specialist_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specialist_employee_c3",
                        to="core.person",
                        verbose_name="especialista de cadenas",
                    ),
                ),
                (
                    "technical_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technical_employee_c3",
                        to="core.person",
                        verbose_name="técnico de cadenas",
                    ),
                ),
                (
                    "trainer_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainer_employee_c3",
                        to="core.person",
                        verbose_name="capacitador",
                    ),
                ),
            ],
            options={
                "verbose_name": "visita componente iii",
                "verbose_name_plural": "visitas componente iii",
            },
        ),
        migrations.DeleteModel(
            name="VisitComponents",
        ),
    ]
