# Generated by Django 4.2 on 2025-04-02 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_activity_import_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitanimalhealth',
            name='is_sal',
            field=models.BooleanField(default=False, verbose_name='es sal'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='import_in',
            field=models.IntegerField(blank=True, choices=[(0, 'desparasitación'), (1, 'sales'), (2, 'vacunos'), (3, 'ovino'), (4, 'alpaca')], null=True, verbose_name='importar excel como'),
        ),
    ]
